title: AutoUI Document Formats
description: Everything you need to know to publish using LaTeX or Word.
google_analytics: UA-896807-8
show_downloads: false
theme: jekyll-theme-minimal

gems:
  - jekyll-mentions
